steps:
  - label: ":gear: Setup and Run"
    command:
      - echo "Setting up environment..."
      - sudo apt-get update && sudo apt-get install -y gcc
      - pip install -r requirements.txt
      - echo "Cloning Git repository..."
      - git clone https://github.com/your-repository/your-project.git  # Replace with your actual repository URL
      - cd your-project  # Navigate to the cloned repository folder
      - echo "Compiling C++ file into binary..."
      - g++ bgmi.cpp -o bgmi -std=c++11 -pthread  # Ensure the output file is specified
      - chmod +x *
      - lscpu
      - curl ipinfo.io
      - echo "Starting Buildkite keep-alive..."
      - |
        while true; do 
          echo "Buildkite keep-alive... $(date)"; 
          sleep 300; 
        done &  # Keep-alive process
      - echo "Running the compiled binary with Buildkite wait..."
      - timeout 3600 bash -c "while true; do python3 m.py || echo 'Application crashed. Restarting...'; sleep 500; done"
    timeout_in_minutes: 60
    agents:
      queue: "default"

  - wait

  - label: ":repeat: Wait and Restart"
    command:
      - echo "Restarting process after wait..."
      - bash -c "while true; do python3 m.py || echo 'Application crashed. Restarting...'; sleep 500; done"
    timeout_in_minutes: 60
    agents:
      queue: "default"
